name: Deployment Pipeline for DevSecOps
on:
  #push:
    #branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make

      - name: Run tests
        run: make test

  build_image:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ vars.IMAGE_NAME }}
          tags: |
            type=edge,branch=$repo.default_branch
            type=semver,pattern=v{{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Build and push image
        id: build-image
        uses: docker/build-push-action@v7.4.0
        with:
          context: .
          #sbom: true
          #provenance: mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      
      # Generate the SBOM file using Syft
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.15.11
        with:
          image: ${{ steps.build-image.outputs.image }}
          output-file: 'sbom.json'
          format: 'cyclonedx-json'
          artifact-name: 'devsecops-sbom'

      # Sign and attach that specific SBOM file to the pushed image
      - name: Attach SBOM Attestation to Image
        uses: actions/attest-sbom@v4.1.0
        with:
          subject-name: docker.io/library/${{ vars.IMAGE_NAME }}
          subject-digest: ${{ steps.build-image.outputs.digest }}
          sbom-path: 'sbom.json'
          push-to-registry: true

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1.24.0
        with:
          command: quickview,cves,recommendations,sbom
          format: json
          output: sbom.json

  deploy_app:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
       
      - name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up azure container instance
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      #- name: Deploy to Azure Container Instance
        #uses: Azure/aci-deploy@v1
        #with:
          #resource-group: DemoAppRG
          #dns-name-label: my-awesome-app
          #registry-login-server: index.docker.io
          #registry-username: ${{ secrets.REGISTRY_USERNAME }}
          #registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          #image: index.docker.io/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}
          #name: my-awesome-app
          #location: 'North Europe'
          #cpu: 1
          #memory: 1.5
          #ports: 5000
          
