name: ZAP Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  Scan_with_ZAP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://my-awesome-app.northeurope.azurecontainer.io:5000/'
